language: android
android:
  components:
  - android-27
  - build-tools-27.0.3
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
before_install:
  - openssl aes-256-cbc -K $encrypted_e3d572028762_key -iv $encrypted_e3d572028762_iv -in app/config.tar.enc -out app/config.tar -d
  - tar -xvf app/config.tar -C app/
script:
  - "./gradlew clean assembleDebug testDebug"
